[platformio]
src_dir = platformio_src

[env:seeed_xiao_esp32c6]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-esp32-c6
framework = arduino
monitor_speed = 115200
build_flags =
  -D FOGSEN_DEBUG_LOGS=1
lib_deps =
  pololu/VL53L0X @ 1.3.1
  pololu/VL53L1X @ 1.3.1
